# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-11 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(blank=True, default='', max_length=14)),
                ('address', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Buyers',
                'verbose_name': 'Buyer',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'compositions',
                'verbose_name': 'composition',
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_category_name', models.CharField(max_length=50)),
                ('dissolution_time_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ingredients', models.ManyToManyField(to='idols.Ingredient')),
            ],
            options={
                'verbose_name_plural': 'MaterialCategorys',
                'verbose_name': 'MaterialCategory',
            },
        ),
        migrations.CreateModel(
            name='Murti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('murti_name', models.CharField(max_length=50)),
                ('murti_id', models.CharField(max_length=2, unique=True)),
                ('altname', models.CharField(blank=True, default='', max_length=50)),
                ('sp_feature', models.TextField(blank=True, default='')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked')], default='Available', max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('featured', models.BooleanField(default=False)),
                ('sold_price', models.PositiveIntegerField(blank=True, null=True)),
                ('booked_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idols.Buyer')),
            ],
            options={
                'verbose_name_plural': 'Murtis',
                'verbose_name': 'Murti',
            },
        ),
        migrations.CreateModel(
            name='MurtiCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('murti_category_name', models.CharField(max_length=50, unique=True)),
                ('category_code', models.CharField(max_length=2)),
                ('feature', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'MurtiCategorys',
                'verbose_name': 'MurtiCategory',
            },
        ),
        migrations.CreateModel(
            name='MurtiImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idol_image', models.FileField(default='idol-images/None/no-img.png', upload_to='idol-images')),
            ],
            options={
                'verbose_name_plural': 'MurtiImages',
                'verbose_name': 'MurtiImage',
            },
        ),
        migrations.CreateModel(
            name='MurtiStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('murti_status', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'MurtiStatus',
                'verbose_name': 'MurtiStatus',
            },
        ),
        migrations.CreateModel(
            name='MurtiTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'MurtiTags',
                'verbose_name': 'MurtiTag',
            },
        ),
        migrations.AddField(
            model_name='murticategory',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idols.MurtiImage'),
        ),
        migrations.AddField(
            model_name='murti',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='idols.MurtiCategory'),
        ),
        migrations.AddField(
            model_name='murti',
            name='images',
            field=models.ManyToManyField(to='idols.MurtiImage'),
        ),
        migrations.AddField(
            model_name='murti',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='idols.MaterialCategory'),
        ),
        migrations.AddField(
            model_name='murti',
            name='tags',
            field=models.ManyToManyField(to='idols.MurtiTag'),
        ),
    ]
