# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-11 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='murti',
            name='murti_id',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='murti',
            name='tags',
            field=models.ManyToManyField(to='idols.MurtiTag'),
        ),
    ]
