# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-26 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0002_auto_20160711_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='murti',
            name='murti_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
