# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0004_murti_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='murtiimage',
            options={'verbose_name': 'Murti Image', 'verbose_name_plural': 'MurtiImages'},
        ),
        migrations.AlterField(
            model_name='murti',
            name='year',
            field=models.IntegerField(choices=[(2017, 2017), (2016, 2016)], default=2017),
        ),
        migrations.AlterField(
            model_name='murticategory',
            name='category_code',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
