# Generated by Django 2.0.5 on 2018-05-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0005_auto_20170618_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='murti',
            name='year',
            field=models.IntegerField(choices=[(2017, 2017), (2016, 2016)], default=2018),
        ),
    ]
